api_platform:
    title: 'CRM API'
    version: '1.0.0'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 10
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/ApiResource'
            - '%kernel.project_dir%/src/Dto'
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        Doctrine\ORM\EntityNotFoundException: 404
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404
        Symfony\Component\Validator\ConstraintViolationListInterface: 422