security:
    providers:
        user_account_provider:
            entity:
                class: App\Entity\UserAccount
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: user_account_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
            entry_point: App\Security\ApiTokenAuthenticator

        main:
            lazy: true
            provider: user_account_provider

    access_control:
        # ⚠️ Autoriser l'accès à TOUTE l'API temporairement sans authentification
        - { path: ^/api, roles: PUBLIC_ACCESS }

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
