security:
    providers:
        user_account_provider:
            entity:
                class: App\Entity\UserAccount
                property: apiToken
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator