services:
  mysql:
    image: mysql:8.0
    container_name: crm_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: crm_db
    ports:
      - "3306:3306"
    volumes:
      - crm_app_data:/var/lib/mysql

volumes:
  crm_app_data: