<?php

namespace ContainerDuxx121;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerSearchProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\CustomerSearchProvider' shared autowired service.
     *
     * @return \App\State\CustomerSearchProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'State'.\DIRECTORY_SEPARATOR.'CustomerSearchProvider.php';

        return $container->privates['App\\State\\CustomerSearchProvider'] = new \App\State\CustomerSearchProvider(($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService')));
    }
}
