services:
    # Auto-configuration par défaut
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    # Charger tous les services du dossier src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Charger explicitement les repositories
    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']

    # Authenticator personnalisé
    App\Security\ApiTokenAuthenticator:
        autowire: true
        autoconfigure: true
        tags:
            - { name: 'security.authenticator' }

    # State Providers
    App\State\FolderState:
        tags: [ 'api_platform.state_provider' ]

    App\State\SenderState:
        tags: [ 'api_platform.state_provider' ]

    App\State\SignatureRequestState:
        tags: [ 'api_platform.state_provider' ]

    App\State\DocumentState:
        tags: [ 'api_platform.state_provider' ]

    App\State\SignerState:
        tags: [ 'api_platform.state_provider' ]

    App\State\UserAccountState:
        tags: [ 'api_platform.state_provider' ]

    App\State\AuditTrailState:
        tags: [ 'api_platform.state_provider' ]

    # State Processors
    App\State\FolderProcessor:
        tags: [ 'api_platform.state_processor' ]

    App\State\SenderProcessor:
        tags: [ 'api_platform.state_processor' ]

    App\State\SignatureRequestProcessor:
        tags: [ 'api_platform.state_processor' ]

    App\State\DocumentProcessor:
        tags: [ 'api_platform.state_processor' ]

    App\State\SignerProcessor:
        tags: [ 'api_platform.state_processor' ]

    App\State\UserAccountProcessor: ~
