parameters:
    app.timezone: 'Europe/Paris'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $logger: '@monolog.logger'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\State\UserAccountProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\UserAccountState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\FolderProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\FolderState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SenderProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SenderState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SignatureRequestProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SignatureRequestState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\DocumentProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\DocumentState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\AuditLogProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\AuditLogState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SignerProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SignerState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\InitialSettingProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\InitialSettingState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SignatureSettingProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SignatureSettingState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SMSNotificationProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\SMSNotificationState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\ReminderSettingProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\ReminderSettingState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\WebhookProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\State\WebhookState:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'